import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/ui/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Footer() {
  return (
    <footer className="bg-black-800 text-white">
      <div className="container mx-auto px-4 py-6 flex justify-between items-center">
        <div>
          <h3 className="font-bold mb-2">Contact Us</h3>
          <p>info@crisisconnect.com</p>
          <p>support@crisisconnect.com</p>
        </div>
        <div>
          <h3 className="font-bold mb-2">In case of Emergency</h3>
          <ul>
            <li>Emergency: 911</li>
            <li>Helpline: 1-800-123-4567</li>
            <li>Customer Support: 1-888-987-6543</li>
          </ul>
        </div>
      </div>
    </footer>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
